package com.amazonaws.mobile.api;

//
//  CloudLogicAPIFactory.java
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.17
//

/**
 * Produces instances of Cloud Logic API configuration.
 */
public class CloudLogicAPIFactory {

    private CloudLogicAPIFactory() {}

    /**
     * Gets the configured micro-service instances.
     * @return
     */
    public static CloudLogicAPIConfiguration[] getAPIs() {
        final CloudLogicAPIConfiguration[] apis = new CloudLogicAPIConfiguration[] {
                new CloudLogicAPIConfiguration("dev-Travel",
                                              "",
                                              "https://kc8m675la9.execute-api.us-east-1.amazonaws.com/dev",
                                              new String[] {
                                                  "/location/getFeed",
                                                  "/todos/delete/{id}",
                                                  "/location/createLocation",
                                                  "/todos/update",
                                                  "/location/getUser",
                                                  "/feed/getFeed",
                                                  "/todos/status",
                                                  "/location/getLocations",
                                                  "/todos",
                                                  "/feed/postFeed",
                                                  "/location/postFeed",
                                                  "/location/getLocation",
                                                  "/todos/getAll",
                                                  "/todos/getById/{id}",
                                              },
                                              com.amazonaws.mobile.api.idkc8m675la9.DevTravelClient.class),
                new CloudLogicAPIConfiguration("dev-aws-nodejs",
                                              "",
                                              "https://x0aideoj55.execute-api.us-east-1.amazonaws.com/dev",
                                              new String[] {
                                                  "/payout",
                                              },
                                              com.amazonaws.mobile.api.idx0aideoj55.DevawsnodejsClient.class),
        };

        return apis;
    }
}
